name: Deployment

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: account-server-im:latest

      - name: SSH into server and restart container
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Stop the existing container (if any)
            docker stop account-server || true
            
            # Remove the existing container (if any)
            docker rm account-server || true
            
            # Run the new container, mapping both TCP and UDP ports
            docker run -d --name account-server-p 2003:2003 -p 2003:2003/udp account-server-im:latest