name: Deployment

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deployment
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            pm2 stop AccountServer || true
            
            cd ~/production/account-server/
            
            git pull origin production
            git status
            
            npm install
            
            mkdir -p ./logs
            
            pm2 start npm -- start:production --name "AccountServer" --log ./logs/myApp-%YYYY-MM-DD%.log